r"""Task D2(b): generators of ker R_sigma' as a LEFT u-module (ker is a left ideal: y sigma' = 0 => (zy) sigma' = 0).
Blocks are processed by increasing principal degree n.  M_gamma := sum_p y1.p * M_{gamma - beta_p} (u is generated by the
degree-1 letters).  If dim M_gamma < ker_gamma, the kernel of block gamma is computed (left null space) and the
difference is counted as NEW GENERATORS in block gamma; then M_gamma := ker_gamma.  So at the end
    #new generators in degree n = minimal number of generators of ker (as graded left module) in degree n,
for n <= nmax.  Also reports, per degree, how much of the kernel is generated by the omega_j alone (A = sum u omega_j)
and by everything of degree < n.
usage: python taskD2_module.py m nmax"""
import pickle
import sys
import time
from collections import defaultdict

import numpy as np
from numba import njit, prange

from cengine import Split, Blocks, build_block, pack_words, rmul_word, MAXOUT, MAXST, MAXW
from gf2null import left_kernel, rowbasis
from gf2 import gf2_rank_inplace


@njit(parallel=True)
def build_left(rows, letter, br, sq, colidx, key, tkey, ncols, nchunk):
    """packed matrix: row r = y_letter * rows[r]"""
    nr = rows.size
    Wd = (ncols + 63) // 64
    P = np.zeros((nr, Wd), dtype=np.uint64)
    bad = np.zeros(nchunk, dtype=np.int64)
    csz = (nr + nchunk - 1) // nchunk
    for c in prange(nchunk):
        out = np.empty(MAXOUT, dtype=np.int64)
        stS = np.empty(MAXST, dtype=np.int64)
        stW = np.empty((MAXST, MAXW), dtype=np.int64)
        stL = np.empty(MAXST, dtype=np.int64)
        Wb = np.empty(MAXW, dtype=np.int64)
        word = np.empty(64, dtype=np.int64)
        lo = c * csz
        hi = min(nr, lo + csz)
        for r in range(lo, hi):
            mono = rows[r]
            L = 0
            for i in range(63):
                if (mono >> i) & 1:
                    word[L] = i
                    L += 1
            n = rmul_word(np.int64(1) << letter, word[:L], br, sq, out, 0, stS, stW, stL, Wb)
            if n < 0:
                bad[c] += 1
                continue
            for i in range(n):
                if key[out[i]] != tkey:
                    bad[c] += 1000000
                    continue
                j = colidx[out[i]]
                P[r, j >> 6] ^= np.uint64(1) << np.uint64(j & 63)
    return P, bad.sum()


@njit(parallel=True)
def matmul_packed(X, ncolsX, Y):
    """X (r x d' bits) times Y (d' x d bits) over GF(2)"""
    r = X.shape[0]
    W = Y.shape[1]
    Z = np.zeros((r, W), dtype=np.uint64)
    for i in prange(r):
        for j in range(ncolsX):
            if (X[i, j >> 6] >> np.uint64(j & 63)) & np.uint64(1):
                for k in range(W):
                    Z[i, k] ^= Y[j, k]
    return Z


if __name__ == "__main__":
    m, nmax = int(sys.argv[1]), int(sys.argv[2])
    t0 = time.time()
    sp = Split(m)
    B = Blocks(sp)
    with open(f"taskC1_m{m}.pkl", "rb") as fh:
        C = pickle.load(fh)
    ker = C["ker"]
    try:
        with open(f"taskD2_m{m}_cols.pkl", "rb") as fh:
            A = pickle.load(fh)["a"]
    except FileNotFoundError:
        try:
            with open(f"taskD2_m{m}.pkl", "rb") as fh:
                A = pickle.load(fh)["a"]
        except FileNotFoundError:
            A = {}
    words, wlen = pack_words(sp.sigma_words())
    one_letters = [sp.pos[(1, p)] for p in range(3)]
    lw = {l: tuple(int(x) for x in sp.lwt[l]) for l in one_letters}
    top = sp.top
    M = {}          # block -> packed basis of M_gamma
    newgen = defaultdict(int)
    stats = defaultdict(lambda: [0, 0, 0, 0])    # n -> [ker, generated from lower, new gens, a]
    blocks = sorted([g for g in B.blocks if sum(g) <= nmax], key=lambda g: (sum(g), g))
    for g in blocks:
        n = sum(g)
        k = ker[g] if (g[0] + 1, g[1] + 1, g[2] + 1) in B.blocks else B.dim(g)
        if (g[0] + 1, g[1] + 1, g[2] + 1) not in B.blocks:
            continue
        d = B.dim(g)
        W = (d + 63) // 64
        parts = []
        for l in one_letters:
            src = (g[0] - lw[l][0], g[1] - lw[l][1], g[2] - lw[l][2])
            if src in M and M[src].shape[0]:
                Lm, bad = build_left(B.blocks[src], l, sp.br, sp.sq, B.local, B.key, np.int32(B.gkey(g)), d, 64)
                assert bad == 0
                parts.append(matmul_packed(M[src], B.dim(src), Lm))
        if parts:
            P = np.vstack(parts)
            basis = rowbasis(P, d)
        else:
            basis = np.zeros((0, W), dtype=np.uint64)
        r = basis.shape[0]
        assert r <= k, (g, r, k)
        st = stats[n]
        st[0] += k
        st[1] += r
        st[3] += A.get(g, 0)
        if r < k:
            h = (g[0] + 1, g[1] + 1, g[2] + 1)
            Pm, bad = build_block(B.blocks[g], words, wlen, sp.br, sp.sq, B.local, B.key, np.int32(B.gkey(h)), B.dim(h), 64)
            assert bad == 0
            Kb, rk = left_kernel(Pm, B.dim(h))
            assert Kb.shape[0] == k, (g, Kb.shape, k)
            newgen[g] = k - r
            st[2] += k - r
            basis = Kb
            print(f"   new generators in block {g} (n={n}): {k - r}  (ker {k}, generated {r}, a {A.get(g, 0)}, dim {d})"
                  f" [{time.time() - t0:.0f}s]", flush=True)
        if k:
            M[g] = basis
    print(f"m={m}: per degree n: [ker, generated by lower degrees, new generators, a=dim sum u omega_j]")
    for n in sorted(stats):
        if stats[n][0]:
            print(f"   n={n}: {stats[n]}")
    print(f"total new generators (n <= {nmax}): {sum(newgen.values())} in {len(newgen)} blocks  [{time.time() - t0:.0f}s]")
    with open(f"taskD2_module_m{m}.pkl", "wb") as fh:
        pickle.dump({"newgen": dict(newgen), "stats": dict(stats), "nmax": nmax}, fh)
