r"""Task D2(a): all restricted subalgebras K of L^s (generated by Q-homogeneous elements of weight <= delta) with
sigma' in K*u (right ideal), i.e. sigma' = sum c_i u_i with c_i in K.  Then u*omega_K = Ann_right(K) is in ker R_sigma'.
Generators of weight <= delta: y1.p (beta_p), y2.p (beta_p + beta_{p-1}), and the 2-dim weight-delta space span{y3.0, y3.1}.
For each minimal generating set: the subalgebra K_{<m} (letters/dimension), so dim u*omega_K = 2^{N_m - dim K_{<m}}.
Also the left version (sigma' in u*K) which gives cokernel (= by duality kernel) elements."""
import itertools
import sys

from cengine import Split, Blocks
from taskD_common import DeltaSpace, words_to_elem, letter_sum, elem_add
from taskC3_lemmas import lie_closure


def span_contains(vecs, target):
    basis = {}
    for v in vecs:
        for piv, b in basis.items():
            if (v >> piv) & 1:
                v ^= b
        if v:
            p = v.bit_length() - 1
            for q in list(basis):
                if (basis[q] >> p) & 1:
                    basis[q] ^= v
            basis[p] = v
    t = target
    for piv, b in basis.items():
        if (t >> piv) & 1:
            t ^= b
    return t == 0


if __name__ == "__main__":
    m = int(sys.argv[1]) if len(sys.argv) > 1 else 9
    sp = Split(m)
    B = Blocks(sp)
    ds = DeltaSpace(sp, B)
    # candidate generators: (name, list of letter positions (sum), weight)
    gens = []
    for p in range(3):
        gens.append((f"y1.{p}", [sp.pos[(1, p)]]))
    for p in range(3):
        gens.append((f"y2.{p}", [sp.pos[(2, p)]]))
    gens.append(("y3.0", [sp.pos[(3, 0)]]))
    gens.append(("y3.1", [sp.pos[(3, 1)]]))
    gens.append(("y3.0+y3.1", [sp.pos[(3, 0)], sp.pos[(3, 1)]]))
    # weight-delta complement pieces: for generator c, the products c*b with b running over a basis of u_{delta - wt c}
    from cengine import wt
    def wt_of(ls):
        return wt(*sp.letters[ls[0]])
    allmono = {}
    for g, arr in B.blocks.items():
        if all(x <= 1 for x in g):
            allmono[g] = [int(x) for x in arr]

    def products(c, side):
        w = wt_of(c)
        rest = tuple(1 - a for a in w)
        out = []
        for b in allmono.get(rest, []):
            bw = [i for i in range(sp.nl) if (b >> i) & 1]
            if side == "right":     # c * b
                el = words_to_elem(sp, [[c] + [[i] for i in bw]])
            else:                   # b * c
                el = words_to_elem(sp, [[[i] for i in bw] + [c]])
            out.append(ds.vec(el))
        return out

    for side in ("right", "left"):
        prods = {name: products(c, side) for name, c in gens}
        found = []
        names = [n for n, _ in gens]
        for r in range(1, len(gens) + 1):
            for S in itertools.combinations(range(len(gens)), r):
                # skip sets containing two different weight-delta generators plus the third (redundant)
                if any(set(F) <= set(S) for F in found):
                    continue
                vecs = [v for i in S for v in prods[names[i]]]
                if span_contains(vecs, ds.sigma):
                    found.append(S)
        print(f"m={m}  sigma' in {'K*u (right ideal) -> kernel of R' if side == 'right' else 'u*K (left ideal) -> cokernel of R'}:"
              f" {len(found)} minimal generating sets", flush=True)
        for S in found:
            K = lie_closure(sp, [gens[i][1] for i in S])
            degs = sorted(int(sp.ldeg[min(v)]) for v in K)
            print(f"   gens {[names[i] for i in S]}: dim K_<m = {len(K)} (N_m = {sp.nl}), degrees {degs}"
                  f"  -> dim Ann = 2^{sp.nl - len(K)} = |G|/2^{len(K)}", flush=True)
            # the same generating set for larger m (the membership sigma' in K*u is independent of m >= 4)
            dl = []
            for mm in range(4, int(sys.argv[2]) + 1 if len(sys.argv) > 2 else 4):
                sp2 = Split(mm)
                g2 = []
                for i in S:
                    nm = names[i]
                    g2.append([sp2.pos[(int(t[1]), int(t[3]))] for t in nm.split("+")])
                dl.append(len(lie_closure(sp2, g2)))
            if dl:
                print(f"      dim K_<m for m = 4..: {dl}", flush=True)
