r"""Task C3: machine checks of the identities used in THEORY.md (split model, engine cengine.py).
 (L1) sigma' = c1*(y1.1*y1.2 + y2.2) + c2*y1.2 + c3,  c_k = e_{k-1} phi^k (column subalgebra C^(0)), c3 = e_2 phi^3 = y3.0+y3.1
 (L2) sigma' = y1.2*y1.1*y1.0 + y1.1*y2.0 + y3.0
 (L3) the restricted subalgebra generated by c1,c2,c3 in L/L_{>=m} is span{c_k : 3 !| k} + span{c_{3*2^r}}
 (L4) omega_H * sigma' = 0 and omega_H * c = 0 for c in H; omega_C (all c_k, k<m) * sigma' = 0
 (L5) the anti-automorphism Theta'(e_p phi^k) = e_{k-p} phi^k (reversed products) fixes sigma'.
"""
import itertools

from cengine import Split


def elem_add(*els):
    acc = {}
    for el in els:
        for t in el:
            acc[t] = acc.get(t, 0) ^ 1
    return sorted(t for t, c in acc.items() if c)


def words_to_elem(sp, words):
    """sum of products of letter-lists; a 'letter' may be a list of letters (sum)"""
    acc = []
    for w in words:
        exp = [[]]
        for l in w:
            ls = l if isinstance(l, list) else [l]
            exp = [e + [x] for e in exp for x in ls]
        for e in exp:
            acc = elem_add(acc, sp.rmul(0, e))
    return acc


def letter(sp, k, p):
    """e_p phi^k as list of letter positions (e_2 = e_0 + e_1 when 3 | k); [] if k >= m"""
    if k >= sp.m:
        return []
    if k % 3 == 0 and p % 3 == 2:
        return [sp.pos[(k, 0)], sp.pos[(k, 1)]]
    return [sp.pos[(k, p % 3)]]


def lie_closure(sp, gens):
    """restricted Lie subalgebra of L_split/L_{>=m} generated by gens (vectors = frozensets of letter positions)"""
    basis = {}

    def reduce(v):
        v = set(v)
        changed = True
        while changed:
            changed = False
            for piv, b in basis.items():
                if piv in v:
                    v ^= b
                    changed = True
        return frozenset(v)

    def add(v):
        v = reduce(v)
        if v:
            basis[min(v)] = v
            # re-reduce others
            return True
        return False

    def br(u, v):
        out = set()
        for a in u:
            for b in v:
                if a != b:
                    out ^= set(int(x) for x in sp.br[a, b] if x >= 0)
        return frozenset(out)

    def sq(u):
        out = set()
        for a in u:
            out ^= set(int(x) for x in sp.sq[a] if x >= 0)
        for a, b in itertools.combinations(sorted(u), 2):
            out ^= set(int(x) for x in sp.br[a, b] if x >= 0)
        return frozenset(out)

    todo = [frozenset(g) for g in gens]
    elems = []
    while todo:
        v = todo.pop()
        if add(v):
            elems.append(v)
            todo.append(sq(v))
            for w in elems:
                todo.append(br(v, w))
    return elems


if __name__ == "__main__":
    for m in range(3, 15):
        sp = Split(m)
        sig = words_to_elem(sp, [list(w) for w in sp.sigma_words()])
        c = {k: letter(sp, k, k - 1) for k in range(1, m)}
        y = lambda k, p: letter(sp, k, p)
        # L1
        l1 = words_to_elem(sp, [w for w in [[c[1], y(1, 1), y(1, 2)], [c[1], y(2, 2)], [c.get(2, []), y(1, 2)], [c.get(3, [])]]
                                if all(isinstance(x, list) and x for x in w)])
        # L2
        l2 = words_to_elem(sp, [w for w in [[y(1, 2), y(1, 1), y(1, 0)], [y(1, 1), y(2, 0)], [y(3, 0)]] if all(w)])
        # L3
        gens = [c[k] for k in (1, 2, 3) if k < m]
        H = lie_closure(sp, gens)
        Hdeg = sorted(int(sp.ldeg[min(v)]) for v in H)
        pred = sorted([k for k in range(1, m) if k % 3] + [3 * 2 ** r for r in range(10) if 3 * 2 ** r < m])
        # L4: omega_H = product of c_k, k in H-degrees (ascending), times sigma' and times c_k
        Hset = sorted(set(pred))
        omega = words_to_elem(sp, [[c[k] for k in Hset]])
        z1 = elem_add(*[sp.mul([t], sig) for t in omega]) if omega else ["empty"]
        zc = all(not elem_add(*[sp.rmul(t, [x]) for t in omega for x in c[k]]) for k in Hset)
        omegaC = words_to_elem(sp, [[c[k] for k in range(1, m)]])
        zC = elem_add(*[sp.mul([t], sig) for t in omegaC]) if omegaC else ["empty"]
        # L5: Theta'(word) = reversed word with e_p phi^k -> e_{k-p} phi^k
        th = []
        for w in sp.sigma_words():
            lets = [sp.letters[i] for i in w]
            th.append([letter(sp, k, k - p) for (k, p) in reversed(lets)])
        l5 = words_to_elem(sp, th)
        print(f"m={m}: L1 {l1 == sig}  L2 {l2 == sig}  L3 H-degrees {Hdeg} == predicted {Hdeg == pred}  "
              f"L4 omega_H nonzero {bool(omega)}, omega_H*sigma'=0 {not z1}, omega_H*H=0 {zc}, omega_C*sigma'=0 {not zC}  "
              f"L5 Theta'(sigma')=sigma' {l5 == sig};  deg omega_H = {sum(Hset)}, S_m = {m * (m - 1) // 2}", flush=True)
        assert l1 == sig and l2 == sig and Hdeg == pred and not z1 and zc and not zC and l5 == sig
